################################################################################
# Metrics and sensitivity analysis script
# Script: 30_metrics.R
################################################################################

source("00_functions.R", local = TRUE)

################################################################################
# Configuration
################################################################################

n_boot <- 1000

# Parameters for power subset calculation
target_power <- 0.80
grid_res <- 30
tij_max <- 0.25  
n_max <- 250

# Flags controlling whether null-distribution thresholds are applied for signal detection
use_threshold_ior <- TRUE
use_threshold_ac <- TRUE

# Classification of high-reporting stages by dynamic pattern
stage_class <- rbind(
  data.table(nichd = niveles_nichd, dynamic = "uniform", class = 1),
  data.table(nichd = niveles_nichd, dynamic = "increase", class = c(0, 0, NA, NA, NA, 1, 1)),
  data.table(nichd = niveles_nichd, dynamic = "decrease", class = c(1, 1, NA, NA, NA, 0, 0)),
  data.table(nichd = niveles_nichd, dynamic = "plateau", class = c(0, NA, 1, 1, 1, NA, 0)),
  data.table(nichd = niveles_nichd, dynamic = "inverse_plateau", class = c(1, NA, 0, 0, 0, NA, 1))
)

output_dir <- paste0("./results/", suffix, "/metrics_results/")

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

reduction_levels <- c(0, seq(10, 90, by = 10))

################################################################################
# Plot labels
################################################################################

nichd_labels <- c(
  "term_neonatal" = "Term neonatal",
  "infancy" = "Infancy",
  "toddler" = "Toddler",
  "early_childhood" = "Early childhood",
  "middle_childhood" = "Middle childhood",
  "early_adolescence" = "Early adolescence",
  "late_adolescence" = "Late adolescence"
)

################################################################################
# Loading null thresholds
################################################################################

ruta_null_dist <- paste0("./results/", suffix, "/null_distribution_results/null_distribution.csv")
thresh_col <- paste0("threshold_", percentil)

null_thresholds_ior <- fread(paste0("./results/", suffix, "/null_distribution_results/null_thresholds.csv"))
null_thresholds_ior <- null_thresholds_ior[, .(stage, threshold_ior = get(thresh_col))]

null_thresholds_ac <- fread(paste0("./results/", suffix, "/null_distribution_results/null_thresholds_ac.csv"))
null_thresholds_ac <- null_thresholds_ac[, .(stage, threshold_ac = get(thresh_col))]

# Classic null thresholds (generated by 20_null.R)
ruta_cls_ior  <- paste0("./results/", suffix, "/null_distribution_results/null_thresholds_classic_ior.csv")
ruta_cls_ac <- paste0("./results/", suffix, "/null_distribution_results/null_thresholds_classic_ac.csv")

null_thresholds_cls_ior <- fread(ruta_cls_ior)[, .(stage, threshold_classic_ior = get(thresh_col))]
null_thresholds_cls_ac <- fread(ruta_cls_ac)[, .(stage, threshold_classic_ac = get(thresh_col))]

null_thresholds <- merge(null_thresholds_ior, null_thresholds_ac, by = "stage")
null_thresholds <- merge(null_thresholds, null_thresholds_cls_ior, by = "stage")
null_thresholds <- merge(null_thresholds, null_thresholds_cls_ac, by = "stage")

################################################################################
# Loading co-administration data and augmentation path (consumed by expand())
################################################################################

# expand() reads the triplet-result RDS files from this base path.
ruta_base_sensitivity <- paste0("./results/", suffix, "/augmentation_results/")

coadmin_stage_pos <- fread(paste0(ruta_base_sensitivity, "positive_coadmin_by_stage.csv"))
coadmin_stage_neg <- fread(paste0(ruta_base_sensitivity, "negative_coadmin_by_stage.csv"))
# expand() joins on stage_num; the stored files use nichd_num.
if (!"stage_num" %in% names(coadmin_stage_pos)) coadmin_stage_pos[, stage_num := nichd_num]
if (!"stage_num" %in% names(coadmin_stage_neg)) coadmin_stage_neg[, stage_num := nichd_num]

################################################################################
# Loading baseline data (no reduction)
################################################################################

data_baseline <- expand(0)  # unreduced baseline used to calibrate power thresholds
# Uniform-dynamic positives are reserved for post-hoc analyses; exclude from all metrics
data_baseline$pos_high <- data_baseline$pos_high[dynamic != "uniform"]
pos_high_base <- data_baseline$pos_high
neg_high_base <- data_baseline$neg_high

################################################################################
# Distribution comparison plots
################################################################################

null_distribution <- fread(ruta_null_dist)

null_sample <- null_distribution[sample(.N, min(.N, 50000))]

comparison_data <- rbind(
  null_sample[, .(stage_num = stage, log_ior_lower90 = log_lower90, ac_lower90 = ac_lower90, source = "Null distribution")],
  pos_high_base[, .(stage_num, log_ior_lower90 = gam_log_ior_lower90, ac_lower90 = gam_ac_lower90, source = "Positives")],
  neg_high_base[, .(stage_num, log_ior_lower90 = gam_log_ior_lower90, ac_lower90 = gam_ac_lower90, source = "Negatives")]
)
comparison_data[, stage_name := factor(stage_num, levels = 1:7, labels = nichd_labels)] # ordered factor for consistent facet ordering

# Drop non-finite values before plotting to avoid ggplot warnings
comparison_data <- comparison_data[ is.finite(log_ior_lower90)]
comparison_data <- comparison_data[ is.finite(ac_lower90)]


color_palette <- c(
  "Null distribution" = "gray60",
  "Positives" = "#4DAF4A",
  "Negatives" = "#E41A1C"
)

# Log(IOR) has extreme outliers (min ~ -6900). geom_density() spreads its 512 evaluation
# points over the full data range, leaving almost none inside the displayed window, so the
# density must be computed on a restricted window. The KDE bandwidth is ~0.05, so points
# beyond +-10 contribute nothing to the curve shown over +-5.
ior_compute_window <- 10
ior_plot_data <- comparison_data[abs(log_ior_lower90) <= ior_compute_window]

p_null_vs_obs_ior <- ggplot( ior_plot_data, aes(x = log_ior_lower90, fill = source)) +
  geom_density(alpha = 0.5, adjust = 1.5) +
  facet_wrap(~ stage_name, scales = "free_y", ncol = 4) +
  scale_fill_manual(values = color_palette) +
  coord_cartesian(xlim = c(-5, 5)) +  # zoom only; does not drop data from the density
  labs(
    title = sprintf("Null distribution vs detected signals (%s)", percentil),
    x = "Log(IOR) - lower bound 90% CI",
    y = "Density",
    fill = "Source")
  ggsave(paste0(output_dir, "fig_null_vs_observed_ior.png"), p_null_vs_obs_ior, width = 16, height = 12, dpi = 300
)

print(p_null_vs_obs_ior)

p_null_vs_obs_ac <- ggplot( comparison_data, aes(x = ac_lower90, fill = source)) +
  geom_density(alpha = 0.5, adjust = 1.5) +
  facet_wrap(~ stage_name, scales = "free_y", ncol = 4) +
  scale_fill_manual(values = color_palette) +
  # Null AC is near a point mass at 0; zoom on the range holding the thresholds and
  # the positive right tail, and cap the y-axis so the central spike does not flatten the rest
  coord_cartesian(xlim = c(-0.1, 0.25), ylim = c(0, 25)) +
  labs(
    title = sprintf("Null distribution vs detected signals (%s)", percentil),
    x = "Additive contrast (90% CI lower bound)",
    y = "Density",
    fill = "Source"
  )
ggsave( paste0(output_dir, "fig_null_vs_observed_ac.png"), p_null_vs_obs_ac, width = 16, height = 12, dpi = 300)

print(p_null_vs_obs_ac)

message(sprintf("Baseline dataset: %d positives, %d negatives", nrow(pos_high_base), nrow(neg_high_base)))

################################################################################
# Power subset calculation for each method
################################################################################

message("GAM-logIOR")
power_gam_ior <- calculate_power_gam(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = null_thresholds,
  metric_n = "n_coadmin",
  grid_resolution = grid_res,
  use_threshold_ior = TRUE,
  use_threshold_ac = FALSE,
  detection = "ior"
)

message("GAM-AC")
power_gam_ac <- calculate_power_gam(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = null_thresholds,
  metric_n = "n_coadmin",
  grid_resolution = grid_res,
  use_threshold_ior = FALSE,
  use_threshold_ac = TRUE,
  detection = "ac"
)

message("Estratificado-IOR")
power_cls_ior <- calculate_power_classic(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = null_thresholds,
  metric_n = "n_coadmin_stage",
  grid_resolution = grid_res,
  detection = "ior",
  na_remove = TRUE
)

message("Estratificado-AC")
power_cls_ac <- calculate_power_classic(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = null_thresholds,
  metric_n = "n_coadmin_stage",
  grid_resolution = grid_res,
  detection = "ac",
  na_remove = TRUE
)

power_ior_list <- list(
  "GAM" = power_gam_ior,
  "Stratified" = power_cls_ior
)

p_surface_ior <- plot_power_surface(
  power_results_list = power_ior_list,
  target_power = target_power, 
  detection = "IOR",
  grid_size = grid_res,
  t_range = c(0, tij_max), 
  n_range = c(0, n_max)
)

ggsave(
  paste0(output_dir, "fig_power_surface_ior_combined.png"), 
  p_surface_ior,
  width = 14,      
  height = 7,     
  dpi = 300
)

print(p_surface_ior)

power_ac_list <- list(
  "GAM" = power_gam_ac,
  "Stratified" = power_cls_ac
)

p_surface_ac <- plot_power_surface(
  power_results_list = power_ac_list,
  target_power = target_power,
  detection = "AC", 
  grid_size = grid_res,
  t_range = c(0, tij_max),
  n_range = c(0, n_max)
)

ggsave(
  paste0(output_dir, "fig_power_surface_ac_combined.png"),
  p_surface_ac, 
  width = 14,
  height = 7,
  dpi = 300
)

print(p_surface_ac)

# Store triplet IDs for each power subset
power_ids <- list(
  "GAM-logIOR" = unique(power_gam_ior$superset_pos[class == 1]$triplet_id),
  "GAM-AC" = unique(power_gam_ac$superset_pos[class == 1]$triplet_id),
  "Estratificado-IOR" = unique(power_cls_ior$superset_pos[class == 1]$triplet_id),
  "Estratificado-AC" = unique(power_cls_ac$superset_pos[class == 1]$triplet_id)
)

# _null and _nom variants use the same power subset as their base method
# the null threshold affects detection only, not which triplets are eligible.
power_ids[["Estratificado-IOR_null"]] <- power_ids[["Estratificado-IOR"]]
power_ids[["Estratificado-AC_null"]] <- power_ids[["Estratificado-AC"]]
power_ids[["GAM-logIOR_nom"]] <- power_ids[["GAM-logIOR"]]
power_ids[["GAM-AC_nom"]] <- power_ids[["GAM-AC"]]


# Triplets that meet the power threshold for both methods in each pair (fairness-equalised denominator)
triplets_intersection_ac <- intersect(power_ids[["GAM-AC"]], power_ids[["Estratificado-AC"]])
message(sprintf("\nIntersection GAM-AC & Estratificado-AC: %d triplets", length(triplets_intersection_ac)))

triplets_intersection_ior <- intersect(power_ids[["GAM-logIOR"]], power_ids[["Estratificado-IOR"]])
message(sprintf("\nIntersection GAM-logIOR & Estratificado-IOR: %d triplets", length(triplets_intersection_ior)))

# Persist cohort sizes for the manuscript (baseline rows and intersection triplet counts)
cohort_sizes <- data.table(
  quantity = c("baseline_positives_stage_rows", "baseline_negatives_stage_rows",
               "intersection_ac_triplets", "intersection_ior_triplets"),
  n = c(nrow(pos_high_base), nrow(neg_high_base),
        length(triplets_intersection_ac), length(triplets_intersection_ior))
)
fwrite(cohort_sizes, paste0(output_dir, "cohort_sizes_summary.csv"))

# Map every method (including _null/_nom aliases) to its underlying power result
# t_star/n_star lookups are keyed by name rather than position — order-independent.
power_source <- list(
  "GAM-logIOR" = power_gam_ior,
  "GAM-AC" = power_gam_ac,
  "Estratificado-IOR" = power_cls_ior,
  "Estratificado-AC" = power_cls_ac,
  "Estratificado-IOR_null"  = power_cls_ior,
  "Estratificado-AC_null" = power_cls_ac,
  "GAM-logIOR_nom" = power_gam_ior,
  "GAM-AC_nom" = power_gam_ac
)

summary_power <- data.table(
  method = names(power_ids),
  n_triplets = sapply(power_ids, length),
  t_star = sapply(names(power_ids), function(m) power_source[[m]]$t_star),
  n_star = sapply(names(power_ids), function(m) power_source[[m]]$n_star)
)

# Retention relative to distinct injected positive triplets (pre-filtering denominator)
n_pos_pool <- uniqueN(pos_high_base$triplet_id)
summary_power[, pct_retained := round(100 * n_triplets / n_pos_pool, 1)]
print(summary_power)

# Read directly by the manuscript (Table 3)
fwrite(summary_power, paste0(output_dir, "power_subset_summary.csv"))

################################################################################
# Data with downsampling
################################################################################

# Loads all reduction levels upfront to avoid repeated I/O inside the nested loops
datos_por_reduccion <- lapply(reduction_levels, expand)
names(datos_por_reduccion) <- as.character(reduction_levels)

# Uniform-dynamic positives are reserved for post-hoc analyses; exclude from all metrics
for (red in names(datos_por_reduccion)) {
  datos_por_reduccion[[red]]$pos_high <- datos_por_reduccion[[red]]$pos_high[dynamic != "uniform"]
}

################################################################################
# Exclusion of triplets that become undetectable after downsampling
################################################################################

# Exclude triplets with N <= 1 A-B-Event reports after reduction
# including them would inflate specificity/NPV at high reduction

exclude_downsampled <- TRUE   

if (exclude_downsampled) {
  
  datos_por_reduccion <- lapply(names(datos_por_reduccion), function(red) {
    datos <- datos_por_reduccion[[red]]
    
    n_neg_antes <- uniqueN(datos$neg_high$triplet_id)
    n_pos_antes <- uniqueN(datos$pos_high$triplet_id)
    
    # Negatives: exclude triplets with at most one A-B-Event report
    datos$neg_high <- datos$neg_high[N > 1]
    # Positives: same logic (injected signals typically have N > 1, but kept for consistency)
    datos$pos_high <- datos$pos_high[N > 1]
    
    n_neg_excluidos <- n_neg_antes - uniqueN(datos$neg_high$triplet_id)
    n_pos_excluidos <- n_pos_antes - uniqueN(datos$pos_high$triplet_id)
    
    message(sprintf(
      " Reduction %s%%: excluded %d negatives + %d positives (N <= 1)",
      red, n_neg_excluidos, n_pos_excluidos
    )) 
    datos
  })
  names(datos_por_reduccion) <- as.character(reduction_levels)
}

################################################################################
# Method definitions
################################################################################

# Methods with their mapped score types and detection settings
metodos <- list(
  # GAM with null distribution threshold
  list(nombre = "GAM-logIOR", tipo = "IOR", null = TRUE,
       score_type = "gam_log_ior_lower90", score_type_auc = "gam_log_ior"),
  list(nombre = "GAM-AC", tipo = "AC", null = TRUE,
       score_type = "gam_ac_lower90", score_type_auc = "gam_ac"),
  # GAM nominal (no null threshold)
  list(nombre = "GAM-logIOR_nom", tipo = "IOR", null = FALSE,
       score_type = "gam_log_ior_lower90", score_type_auc = "gam_log_ior"),
  list(nombre = "GAM-AC_nom", tipo = "AC", null = FALSE,
       score_type = "gam_ac_lower90", score_type_auc = "gam_ac"),
  # Stratified nominal
  list(nombre = "Estratificado-IOR", tipo = "IOR", null = FALSE,
       score_type = "classic_log_ior_lower90", score_type_auc = "classic_log_ior"),
  list(nombre = "Estratificado-AC", tipo = "AC", null = FALSE,
       score_type = "classic_ac_lower90", score_type_auc = "classic_ac"),
  # Stratified with null distribution threshold (requires 20_null classic outputs)
  list(nombre = "Estratificado-IOR_null", tipo = "IOR", null = TRUE,
       score_type = "classic_log_ior_lower90", score_type_auc = "classic_log_ior"),
  list(nombre = "Estratificado-AC_null", tipo = "AC", null = TRUE,
       score_type = "classic_ac_lower90", score_type_auc = "classic_ac")
)

################################################################################
# Global percentile sweep (no reduction): null-threshold trade-off comparison
################################################################################

# Global unreduced metrics for every method under each available null percentile

# Builds the merged per-stage null thresholds for an arbitrary percentile 
# mirrors the canonical construction above, but parameterized by the threshold column
build_null_thresholds <- function(pct) {
  tc <- paste0("threshold_", pct)
  nt_ior  <- fread(paste0("./results/", suffix, "/null_distribution_results/null_thresholds.csv"))[, .(stage, threshold_ior = get(tc))]
  nt_ac <- fread(paste0("./results/", suffix, "/null_distribution_results/null_thresholds_ac.csv"))[, .(stage, threshold_ac = get(tc))]
  nt_cls_ior  <- fread(ruta_cls_ior)[, .(stage, threshold_classic_ior = get(tc))]
  nt_cls_ac <- fread(ruta_cls_ac)[, .(stage, threshold_classic_ac = get(tc))]
  Reduce(function(a, b) merge(a, b, by = "stage"),
         list(nt_ior, nt_ac, nt_cls_ior, nt_cls_ac))
}

# Percentiles available in the null-distribution output
percentiles_avail <- names(fread(
  paste0("./results/", suffix, "/null_distribution_results/null_thresholds.csv"), nrows = 0))
percentiles_avail <- sub("^threshold_", "", grep("^threshold_p", percentiles_avail, value = TRUE))

null_thresholds_canonical <- null_thresholds   # canonical (percentil) thresholds, restored below
etapas_alto_reporte <- stage_class[class == 1, unique(nichd)]
rng_state <- .Random.seed                      # snapshot before the sweep consumes any RNG

res_global_pct <- list()
for (pct in percentiles_avail) {
  null_thresholds <- build_null_thresholds(pct)  # global, consumed by expand()
  datos_p <- expand(0)
  # Uniform-dynamic positives are reserved for post-hoc analyses; exclude from all metrics
  datos_p$pos_high <- datos_p$pos_high[dynamic != "uniform"]
  # Mirrors the main-loop exclusion: a triplet with N <= 1 A-B-Event reports is trivially absent.
  datos_p$neg_high <- datos_p$neg_high[N > 1]
  datos_p$pos_high <- datos_p$pos_high[N > 1]
  neg_global <- datos_p$neg_high[nichd %in% etapas_alto_reporte]
  for (met in metodos) {
    dt_global <- rbind(datos_p$pos_high, neg_global, fill = TRUE)
    dt_global <- detect_signal(dt_global, met$nombre, met$tipo, use_null = met$null)
    mg <- calculate_metrics(dt_global, n_boot, aggregate_triplet = TRUE,
      score_type = met$score_type, score_type_auc = met$score_type_auc)
    mg[, `:=`(method = met$nombre, reduction_pct = 0, percentil = pct, dataset = "original")]
    res_global_pct[[length(res_global_pct) + 1]] <- mg
  }
}

.Random.seed <- rng_state             # restore: the main metrics below reproduce exactly
null_thresholds <- null_thresholds_canonical

metrics_global_percentiles <- rbindlist(res_global_pct, fill = TRUE)
fwrite(metrics_global_percentiles, paste0(output_dir, "metrics_global_percentiles.csv"))

################################################################################
# Metrics calculation
################################################################################

# Original metrics (no power-based filtering applied to positive triplets)
res_global_original <- list()
res_dinamica_original <- list()
res_etapa_original <- list()

# Global ROC curve coordinates (continuous-predictor discrimination).
# Computed only for the four base methods: the _null and _nom variants share the same continuous score columns
res_roc_original <- list()

for (red_pct in reduction_levels) {
  
  message(sprintf("\nReduction %d%%", red_pct))
  datos <- datos_por_reduccion[[as.character(red_pct)]]

  for (met in metodos) {

    message(sprintf("  %s", met$nombre))

    # Global metrics: restrict negatives to high-reporting stages to match the positive evaluation set
    etapas_alto_reporte <- stage_class[class == 1, unique(nichd)]
    neg_global <- datos$neg_high[nichd %in% etapas_alto_reporte]

    dt_global <- rbind(datos$pos_high, neg_global, fill = TRUE)
    dt_global <- detect_signal(dt_global, met$nombre, met$tipo, use_null = met$null)
    
    # Aggregate at triplet level to avoid double-counting triplets that appear in multiple stages
    metrics_global <- calculate_metrics(dt_global, n_boot, aggregate_triplet = TRUE,  # TRUE here to avoid double-counting across stages
      score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_global[, `:=`( method = met$nombre, reduction_pct = red_pct, dataset = "original")]
      res_global_original[[length(res_global_original) + 1]] <- metrics_global

    # ROC curves for base methods only; _null/_nom share the same score column and would produce identical curves
    if (!grepl("_null|_nom", met$nombre)) {
      for (pred in c("point", "lower90")) {
        score_col <- if (pred == "point") met$score_type_auc else met$score_type
        roc_dt <- compute_roc_curve(dt_global, score_col, aggregate_triplet = TRUE)
        if (!is.null(roc_dt)) {
          roc_dt[, `:=`(method = met$nombre, reduction_pct = red_pct,
                        predictor = pred, dataset = "original")]
          res_roc_original[[length(res_roc_original) + 1]] <- roc_dt
        }
      }
    }

    # Metrics by dynamic pattern; uniform excluded (no stage subset applies)
    dinamicas <- setdiff(unique(datos$pos_high$dynamic), "uniform")

    for (dyn in dinamicas) {
      # High-reporting stages for this dynamic define the evaluation window
      etapas_altas <- stage_class[dynamic == dyn & class == 1, nichd]
      pos_dyn <- datos$pos_high[nichd %in% etapas_altas & dynamic == dyn]
      # Negatives restricted to the same high-reporting stages for comparability
      neg_dyn <- datos$neg_high[nichd %in% etapas_altas]
  
      dt_dyn <- rbind(pos_dyn, neg_dyn, fill = TRUE)
      dt_dyn <- detect_signal(dt_dyn, met$nombre, met$tipo, use_null = met$null)
      
      metrics_dyn <- calculate_metrics(dt_dyn, n_boot, aggregate_triplet = TRUE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc) 
      metrics_dyn[, `:=`(
        method = met$nombre,
        reduction_pct = red_pct,
        dynamic = dyn,
        dataset = "original"
      )]
      res_dinamica_original[[length(res_dinamica_original) + 1]] <- metrics_dyn
    }
    
    # Per-stage metrics: no triplet aggregation; each row corresponds to one stage observation
    for (s in 1:7) {
      nichd_label <- niveles_nichd[s]
      # class == 1 ensures positives are from high-reporting stages for this method
      pos_stage <- datos$pos_high[stage_num == s & class == 1]
      neg_stage <- datos$neg_high[stage_num == s]
      dt_stage <- rbind(pos_stage, neg_stage, fill = TRUE)
      dt_stage <- detect_signal(dt_stage, met$nombre, met$tipo, use_null = met$null)
      metrics_stage <- calculate_metrics(dt_stage, n_boot, aggregate_triplet = FALSE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_stage[, `:=`(method = met$nombre, reduction_pct = red_pct, stage_num = s, nichd = nichd_label, dataset = "original")]
        res_etapa_original[[length(res_etapa_original) + 1]] <- metrics_stage
    }
  }
}

metrics_global_original <- rbindlist(res_global_original, fill = TRUE)
metrics_dynamic_original <- rbindlist(res_dinamica_original, fill = TRUE)
metrics_stage_original <- rbindlist(res_etapa_original, fill = TRUE)

fwrite(metrics_global_original, paste0(output_dir, "metrics_global_original.csv"))
fwrite(metrics_dynamic_original, paste0(output_dir, "metrics_dynamic_original.csv"))
fwrite(metrics_stage_original, paste0(output_dir, "metrics_stage_original.csv"))

# ROC coordinates consumed by 40_graphs.R
roc_global_original <- rbindlist(res_roc_original, fill = TRUE)
fwrite(roc_global_original, paste0(output_dir, "roc_global_original.csv"))

################################################################################
# Metrics calculation on the statistical power subset
################################################################################

res_global_filtered <- list()
res_dinamica_filtered <- list()
res_etapa_filtered <- list()

for (red_pct in reduction_levels) {
  
  message(sprintf("\nReduction %d%%", red_pct))
  datos <- datos_por_reduccion[[as.character(red_pct)]]

  for (met in metodos) {
    message(sprintf("  %s", met$nombre))
    ids_filtrar <- power_ids[[met$nombre]]

    # Global metrics on power-filtered positive set
    etapas_alto_reporte <- stage_class[class == 1, unique(nichd)]
    neg_global <- datos$neg_high[nichd %in% etapas_alto_reporte]

    pos_fil <- datos$pos_high[triplet_id %in% ids_filtrar]
    dt_global <- rbind(pos_fil, neg_global, fill = TRUE)
    dt_global <- detect_signal(dt_global, met$nombre, met$tipo, use_null = met$null)
    
    metrics_global <- calculate_metrics(dt_global, n_boot, aggregate_triplet = TRUE, 
      score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_global[, `:=`( method = met$nombre, reduction_pct = red_pct, dataset = "filtered")]
      res_global_filtered[[length(res_global_filtered) + 1]] <- metrics_global
    
    # Filtered metrics by dynamic pattern; uniform excluded (no stage subset applies)
    dinamicas <- setdiff(unique(datos$pos_high$dynamic), "uniform")

    for (dyn in dinamicas) {
      etapas_altas <- stage_class[dynamic == dyn & class == 1, nichd]
      pos_dyn <- datos$pos_high[triplet_id %in% ids_filtrar & nichd %in% etapas_altas & dynamic == dyn]
      neg_dyn <- datos$neg_high[nichd %in% etapas_altas]
      dt_dyn <- rbind(pos_dyn, neg_dyn, fill = TRUE)
      dt_dyn <- detect_signal(dt_dyn, met$nombre, met$tipo, use_null = met$null)
      
      metrics_dyn <- calculate_metrics(dt_dyn, n_boot, aggregate_triplet = TRUE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_dyn[, `:=`( method = met$nombre, reduction_pct = red_pct, dynamic = dyn, dataset = "filtered")]
        res_dinamica_filtered[[length(res_dinamica_filtered) + 1]] <- metrics_dyn
    }
    
    # Per-stage metrics on power-filtered positives
    for (s in 1:7) {
      nichd_label <- niveles_nichd[s]
      pos_stage <- datos$pos_high[triplet_id %in% ids_filtrar & stage_num == s & class == 1]
      
      neg_stage <- datos$neg_high[stage_num == s]
      
      dt_stage <- rbind(pos_stage, neg_stage, fill = TRUE)
      dt_stage <- detect_signal(dt_stage, met$nombre, met$tipo, use_null = met$null)
      
      metrics_stage <- calculate_metrics(dt_stage, n_boot, aggregate_triplet = FALSE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_stage[, `:=`(
        method = met$nombre,
        reduction_pct = red_pct,
        stage_num = s,
        nichd = nichd_label,
        dataset = "filtered"
      )]
      res_etapa_filtered[[length(res_etapa_filtered) + 1]] <- metrics_stage
    }
  }
}

metrics_global_filtered <- rbindlist(res_global_filtered, fill = TRUE)
metrics_dynamic_filtered <- rbindlist(res_dinamica_filtered, fill = TRUE)
metrics_stage_filtered <- rbindlist(res_etapa_filtered, fill = TRUE)

fwrite(metrics_global_filtered, paste0(output_dir, "metrics_global_filtered.csv"))
fwrite(metrics_dynamic_filtered, paste0(output_dir, "metrics_dynamic_filtered.csv"))
fwrite(metrics_stage_filtered, paste0(output_dir, "metrics_stage_filtered.csv"))

################################################################################
# Metrics calculation on the intersection subset
################################################################################

pares_interseccion <- list(
  list(
    metodos = metodos[sapply(metodos, function(m) m$nombre %in% c(
      "GAM-AC", "Estratificado-AC", "Estratificado-AC_null", "GAM-AC_nom"
    ))],
    triplets = triplets_intersection_ac,
    label = "AC"
  ),
  list(
    metodos = metodos[sapply(metodos, function(m) m$nombre %in% c(
      "GAM-logIOR", "Estratificado-IOR", "Estratificado-IOR_null", "GAM-logIOR_nom"
    ))],
    triplets = triplets_intersection_ior,
    label = "IOR"
  )
)

res_global_inter <- list()
res_dinamica_inter <- list()
res_etapa_inter <- list()

for (red_pct in reduction_levels) {
  message(sprintf("\nReduction %d%%", red_pct))
  datos <- datos_por_reduccion[[as.character(red_pct)]]
  
  for (par in pares_interseccion) {
    for (met in par$metodos) {
      message(sprintf("%s [intersection %s]", met$nombre, par$label))
      
      pos_int <- datos$pos_high[triplet_id %in% par$triplets]  # pair-specific intersection triplet set

      # Global metrics
      etapas_alto_reporte <- stage_class[class == 1, unique(nichd)]
      neg_global <- datos$neg_high[nichd %in% etapas_alto_reporte]
      dt_global <- rbind(pos_int, neg_global, fill = TRUE)
      dt_global <- detect_signal(dt_global, met$nombre, met$tipo, use_null = met$null)
      
      metrics_global <- calculate_metrics(dt_global, n_boot, aggregate_triplet = TRUE, score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_global[, `:=`(method = met$nombre, reduction_pct = red_pct, dataset = "intersection")]
      res_global_inter[[length(res_global_inter) + 1]] <- metrics_global
      
      # Metrics by dynamic pattern; uniform excluded (no stage subset applies)
      dinamicas <- setdiff(unique(datos$pos_high$dynamic), "uniform")
      for (dyn in dinamicas) {
        etapas_altas <- stage_class[dynamic == dyn & class == 1, nichd]
        pos_dyn <- pos_int[nichd %in% etapas_altas & dynamic == dyn]
        neg_dyn <- datos$neg_high[nichd %in% etapas_altas]
        dt_dyn <- rbind(pos_dyn, neg_dyn, fill = TRUE)
        dt_dyn <- detect_signal(dt_dyn, met$nombre, met$tipo, use_null = met$null)
        
        metrics_dyn <- calculate_metrics(dt_dyn, n_boot, aggregate_triplet = TRUE,
          score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_dyn[, `:=`(method = met$nombre, reduction_pct = red_pct, dynamic = dyn, dataset = "intersection")]
        res_dinamica_inter[[length(res_dinamica_inter) + 1]] <- metrics_dyn
      }
      
      # Per-stage metrics on intersection positives
      for (s in 1:7) {
        nichd_label <- niveles_nichd[s]
        pos_stage <- pos_int[stage_num == s & class == 1]
        neg_stage <- datos$neg_high[stage_num == s]
        dt_stage <- rbind(pos_stage, neg_stage, fill = TRUE)
        dt_stage <- detect_signal(dt_stage, met$nombre, met$tipo, use_null = met$null)
        
        metrics_stage <- calculate_metrics(dt_stage, n_boot, aggregate_triplet = FALSE,
          score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_stage[, `:=`(method = met$nombre, reduction_pct = red_pct,
                             stage_num = s, nichd = nichd_label, dataset = "intersection")]
        res_etapa_inter[[length(res_etapa_inter) + 1]] <- metrics_stage
      }
    }
  }
}

metrics_global_intersection <- rbindlist(res_global_inter, fill = TRUE)
metrics_dynamic_intersection <- rbindlist(res_dinamica_inter, fill = TRUE)
metrics_stage_intersection <- rbindlist(res_etapa_inter, fill = TRUE)

fwrite(metrics_global_intersection,  paste0(output_dir, "metrics_global_intersection.csv"))
fwrite(metrics_dynamic_intersection, paste0(output_dir, "metrics_dynamic_intersection.csv"))
fwrite(metrics_stage_intersection,   paste0(output_dir, "metrics_stage_intersection.csv"))
